name: SDRangel Flatpak build

on:
  push:
    branches:
      - flatpak
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_flatpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: |
          if [[ "$GITHUB_REF_NAME" == "flatpak" ]]; then
            echo "version=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          else
            echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
          fi
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: sdrangel-${{ steps.get_version.outputs.version }}-x86_64.flatpak
          manifest-path: flatpak/org.sdrangel.SDRangel.yaml
          cache-key: flatpak-builder-${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdrangel-${{ steps.get_version.outputs.version }}-x86_64.flatpak
          path: sdrangel-${{ steps.get_version.outputs.version }}-x86_64.flatpak
      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: sdrangel-${{ steps.get_version.outputs.version }}-x86_64.flatpak
